### ISSUE TITLE
block: product hero

### ISSUE THREAD

**Issue by david-granberg** [hlxsites/Vonage#99]
https://www.vonage.com/unified-communications/business-phones/polycom-vvx-150/

![image](https://github.com/hlxsites/Vonage/assets/126118840/9a0e5d4a-e015-4563-bbe8-b80e1ae957db)

**Comment by synox** [comment]
@david-granberg @dkuntze 

Instead of implementing this Hero block, maybe we can port this over to the new style, which looks better across all screen sizes. 

<img width="1028" alt="Screenshot 2023-06-28 at 15 52 32" src="https://github.com/hlxsites/Vonage/assets/2250964/3b77891d-2f07-4c6a-9309-c2f707196251">

It is used for some phones, e.g. https://www.vonage.com/unified-communications/business-phones/yealink-sip-t46u/

and we already implemented this in https://main--vonage--hlxsites.hlx.page/unified-communications/business-phones/yealink-sip-t46u
